version: '3.3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - front
  redis:
    image: redis:5
    container_name: redis
    ports:
     - 6379:6379
  backend:
    image: back
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_PASSWORD=hidden
      - DB_USERNAME=postgres
      - DB_HOST=poskireisi
    ports:
      - 8000:8000
  front:
    image: front
    build: ./frontend-example
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost/api
  db:
    image: postgres
    container_name: poskireisi
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: hidden

volumes:
  database:







